//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./helloworld_types');
//HELPER FUNCTIONS AND STRUCTURES

var HelloWorldService_ping_args = function(args) {
};
HelloWorldService_ping_args.prototype = {};
HelloWorldService_ping_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HelloWorldService_ping_args.prototype.write = function(output) {
  output.writeStructBegin('HelloWorldService_ping_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var HelloWorldService_ping_result = function(args) {
};
HelloWorldService_ping_result.prototype = {};
HelloWorldService_ping_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HelloWorldService_ping_result.prototype.write = function(output) {
  output.writeStructBegin('HelloWorldService_ping_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var HelloWorldService_echoSomeThing_args = function(args) {
  this.demo = null;
  this.name = null;
  if (args) {
    if (args.demo !== undefined && args.demo !== null) {
      this.demo = new ttypes.Demo(args.demo);
    }
    if (args.name !== undefined && args.name !== null) {
      this.name = args.name;
    }
  }
};
HelloWorldService_echoSomeThing_args.prototype = {};
HelloWorldService_echoSomeThing_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.demo = new ttypes.Demo();
        this.demo.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HelloWorldService_echoSomeThing_args.prototype.write = function(output) {
  output.writeStructBegin('HelloWorldService_echoSomeThing_args');
  if (this.demo !== null && this.demo !== undefined) {
    output.writeFieldBegin('demo', Thrift.Type.STRUCT, 1);
    this.demo.write(output);
    output.writeFieldEnd();
  }
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 2);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var HelloWorldService_echoSomeThing_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
HelloWorldService_echoSomeThing_result.prototype = {};
HelloWorldService_echoSomeThing_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HelloWorldService_echoSomeThing_result.prototype.write = function(output) {
  output.writeStructBegin('HelloWorldService_echoSomeThing_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var HelloWorldServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
HelloWorldServiceClient.prototype = {};
HelloWorldServiceClient.prototype.seqid = function() { return this._seqid; };
HelloWorldServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };
HelloWorldServiceClient.prototype.ping = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ping();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ping();
  }
};

HelloWorldServiceClient.prototype.send_ping = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ping', Thrift.MessageType.CALL, this.seqid());
  var args = new HelloWorldService_ping_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

HelloWorldServiceClient.prototype.recv_ping = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new HelloWorldService_ping_result();
  result.read(input);
  input.readMessageEnd();

  callback(null);
};
HelloWorldServiceClient.prototype.echoSomeThing = function(demo, name, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_echoSomeThing(demo, name);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_echoSomeThing(demo, name);
  }
};

HelloWorldServiceClient.prototype.send_echoSomeThing = function(demo, name) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('echoSomeThing', Thrift.MessageType.CALL, this.seqid());
  var params = {
    demo: demo,
    name: name
  };
  var args = new HelloWorldService_echoSomeThing_args(params);
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

HelloWorldServiceClient.prototype.recv_echoSomeThing = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new HelloWorldService_echoSomeThing_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('echoSomeThing failed: unknown result');
};
var HelloWorldServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
HelloWorldServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
HelloWorldServiceProcessor.prototype.process_ping = function(seqid, input, output) {
  var args = new HelloWorldService_ping_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.ping.length === 0) {
    Q.fcall(this._handler.ping.bind(this._handler))
      .then(function(result) {
        var result_obj = new HelloWorldService_ping_result({success: result});
        output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("ping", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.ping(function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new HelloWorldService_ping_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("ping", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
HelloWorldServiceProcessor.prototype.process_echoSomeThing = function(seqid, input, output) {
  var args = new HelloWorldService_echoSomeThing_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.echoSomeThing.length === 2) {
    Q.fcall(this._handler.echoSomeThing.bind(this._handler), args.demo, args.name)
      .then(function(result) {
        var result_obj = new HelloWorldService_echoSomeThing_result({success: result});
        output.writeMessageBegin("echoSomeThing", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("echoSomeThing", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.echoSomeThing(args.demo, args.name, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new HelloWorldService_echoSomeThing_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("echoSomeThing", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("echoSomeThing", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
